language: node_js
node_js:
  - "node"

before_install:
  - rvm install 2.1
  - rvm use 2.1
  - gem install scss_lint

before_script:
  - npm install -g bower
  - bower install
  - npm install -g gulp
# including lint:babel is buggy (use strict errors)
# lint:scss is not part of the test suite
script: gulp test && gulp lint:scss && gulp lint:babel && gulp coverage
